name: C++ Build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: 'latest'
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libeigen3-dev nlohmann-json3-dev libspdlog-dev 
      - name: Install Libzip
        run: |
          git clone https://github.com/nih-at/libzip.git
          cd libzip
          mkdir build
          cd build
          cmake ..
          sudo make
          make install
      - name: Install Google Test v1.12.1
        run: |
          git clone -b release-1.12.1 https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          sudo make
          sudo make install
      - name: Install mio
        run: |
          git clone -b master https://github.com/vimpunk/mio.git
          cd mio
          mkdir build
          cd build
          cmake ..
          sudo make
          sudo make install
      - name: Build C++ project
        run: |
          mkdir build
          cd build
          cmake ..
          sudo make
