name: C++ Build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
      - name: Build Project
        run: cmake --build build

      